language: php 

php:
  - 5.6
  - 7.0

compiler:
  - gcc

#Compile
before_script:
    - ./travis/build_libmmseg.sh
    - ./travis/build_php-mmseg.sh
    - phpenv config-add mmseg/ini/mmseg.ini

# Run PHPs run-tests.php 
script:
    - echo "ok"
